"""One-shot PDF -> FAQ (Q&A pairs) generation endpoint (non-streaming JSON).

Takes an uploaded PDF (base64) plus a user-selected model and returns a list of
Q&A pairs generated by the LLM. Reuses the existing credential loading, LLM
factory, and PDF message-building used by the streaming agent endpoints.
"""

import logging

from fastapi import APIRouter, HTTPException, Request, status
from fastapi.concurrency import run_in_threadpool
from langchain_core.messages import SystemMessage

from src.core.schemas.PdfToFaqRequest import FaqList, PdfToFaqRequest
from src.deps import auth_dependency, db_dependency
from src.rate_limit import limiter
from src.agent_runtime.helpers.caller_llm import (
    CredentialDecryptError,
    LlmInitError,
    MissingCredentialError,
    create_caller_llm,
)
from src.utils.pdf_to_images import build_pdf_message
from src.utils.errors import own_message_or_reason, public_reason

logger = logging.getLogger(__name__)

router = APIRouter()

SYSTEM_PROMPT = (
    "You are an expert at reading documents and producing high-quality FAQ "
    "entries. You generate clear, self-contained question/answer pairs that a "
    "reader could use to understand the document. Every answer must be grounded "
    "strictly in the provided document content. Never invent facts that are not "
    "supported by the document."
)

USER_PROMPT = (
    "Read the document above and generate frequently-asked-question / answer "
    "pairs from it. Generate as MANY pairs as needed to comprehensively cover "
    "ALL of the information present in the document — do not stop at a fixed "
    "number and do not omit important details. Each question should be concise "
    "and self-contained; each answer must be grounded strictly in the document."
)


@router.post("/generate")
@limiter.limit("60/minute")
async def generate_faq(
    request_body: PdfToFaqRequest,
    db: db_dependency,
    auth: auth_dependency,
    request: Request,  # required by slowapi; must be named `request`
):
    account_id = auth["id"]

    provider = request_body.model.provider
    model_name = request_body.model.model

    # --- Credentials + LLM (the caller's own key; see helpers/caller_llm.py).
    # The streaming flag does not block .ainvoke. ---
    try:
        llm = create_caller_llm(db, account_id, provider, model_name, temperature=0)
    except MissingCredentialError:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"{provider.title()} API key required. Add it in account settings.",
        )
    except CredentialDecryptError as exc:
        logger.warning("[PDF_TO_FAQ] could not read the %s API key", provider, exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Failed to retrieve API key.",
        ) from exc.__cause__
    except LlmInitError as exc:
        logger.warning("[PDF_TO_FAQ] LLM initialization failed", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"LLM initialization failed: {own_message_or_reason(exc.__cause__ or exc)}",
        ) from exc.__cause__

    # Release the DB connection before the long-running LLM call (matches context.py).
    db.close()

    use_vision = request_body.pdfUseVision or False
    # CPU-bound PyMuPDF parse — run on the threadpool, never on the event loop
    # (matches src/routers/agents/context.py).
    human_message = await run_in_threadpool(
        build_pdf_message,
        prompt=USER_PROMPT,
        pdf_base64=request_body.pdf,
        pdf_filename=request_body.pdfFilename,
        use_vision=use_vision,
        max_pages=10 if use_vision else 50,
    )

    structured_llm = llm.with_structured_output(FaqList)

    try:
        result: FaqList = await structured_llm.ainvoke(
            [SystemMessage(content=SYSTEM_PROMPT), human_message]
        )
    except Exception as exc:
        logger.exception("[PDF_TO_FAQ] LLM structured-output call failed: %s", exc)
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=f"Failed to generate FAQ: {public_reason(exc)}",
        ) from exc

    return {
        "model": {"provider": provider, "model": model_name},
        "pairs": [p.model_dump() for p in result.pairs],
    }
